
image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add make
  - make docs/html
  - mv docs/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master