image: python:3.7-alpine

pages:
  script:
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install cython
  - pip install numpy
  - apk --no-cache add make
  - cd docs
  - make html
  - cd ..
  - mv docs/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
