name: GitHub Page Builder
run-name: ${{ github.actor }} is building GitHub Pages with Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: farms-core-integration

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make automake gcc g++ subversion python3-dev
          pip install ducks/source/requirements.txt

      - name: Build HTML
        run: |
          cd docs
          make html
          cd ..
          mv docs/build/html/ public/

      - name: Cache documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
