name: GitHub Page Builder
run-name: ${{ github.actor }} is building GitHub Pages with Actions

on:
  push:
    branches:
      - main
      - farms-core-integration

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: farms-core-integration

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make automake gcc g++ subversion python3-dev
          pip install cython
          pip install numpy
          pip install --use-pep517 -r ducks/source/requirements.txt
          git clone https://github.com/farmsim/farms_core.git
          cd farms_core
          python setup.py build_ext --inplace
          cd ..
          pip install --use-pep517 .

      - name: Build HTML
        run: |
          cd ducks
          make html
          cd ..
          mv ducks/build/html/ public/

      - name: Cache documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        # if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
